"""Create initial tables

Revision ID: f543bd8bcf46
Revises: 
Create Date: 2025-06-15 16:58:48.726384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f543bd8bcf46'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geographic_areas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('line', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('station_name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('zip', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stations_by_geographic_areas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('geographic_area_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['geographic_area_id'], ['geographic_areas.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stations_by_geographic_areas_geographic_area_id'), 'stations_by_geographic_areas', ['geographic_area_id'], unique=False)
    op.create_index(op.f('ix_stations_by_geographic_areas_station_id'), 'stations_by_geographic_areas', ['station_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stations_by_geographic_areas_station_id'), table_name='stations_by_geographic_areas')
    op.drop_index(op.f('ix_stations_by_geographic_areas_geographic_area_id'), table_name='stations_by_geographic_areas')
    op.drop_table('stations_by_geographic_areas')
    op.drop_table('stations')
    op.drop_table('geographic_areas')
    # ### end Alembic commands ###
